version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./WebApi/
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on: 
      - db
    links: 
      - db
    ports:
      - "8080:5000"
  db:
    container_name: db
    image: "mysql/mysql-server:8.0.26"
    environment:
      MYSQL_DATABASE: queuedb
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - ./mysql:/var/lib/mysql

