version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./WebApi/
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS
      - ASPNETCORE_ConnectionStrings__QueueDb
      - ASPNETCORE_jwtTokenConfig__secret
      - ASPNETCORE_jwtTokenConfig__issuer
      - ASPNETCORE_jwtTokenConfig__audience
    depends_on: 
      - db
    links: 
      - db
    ports:
      - "5000:5000"
    entrypoint: ["/app/wait-for.sh", "db:3306", "--"]
    command: ["dotnet", "WebApi.dll"]
    #restart: on-failure
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5000/health_check"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
  db:
    container_name: db
    image: "mysql/mysql-server:8.0.26"
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
    # healthcheck:
    #   test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
  fillr:
    container_name: fillr
    build:
      context: ./UserFiller/
      dockerfile: ./Dockerfile
    environment:
      - FILLR_User__UserName
      - FILLR_User__Email
      - FILLR_User__Password
      - FILLR_Connection__WebApi
    depends_on:
      - web
    links:
      - web
    entrypoint: ["/app/wait-for.sh", "web:5000", "--"]
    command: ["dotnet", "UserFiller.dll"]
  front:
    container_name: front
    image: "nginx:alpine"
    ports: 
      - "80:80"
    volumes:
      - ./Frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fillr
    links:
      - fillr
    
    

