version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./WebApi/
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ConnectionStrings__QueueDb=${ASPNETCORE_ConnectionStrings__QueueDb}
      - ASPNETCORE_jwtTokenConfig__secret=${ASPNETCORE_jwtTokenConfig__secret}
      - ASPNETCORE_jwtTokenConfig__issuer=${ASPNETCORE_jwtTokenConfig__issuer}
      - ASPNETCORE_jwtTokenConfig__audience=${ASPNETCORE_jwtTokenConfig__audience}
    depends_on: 
      - db
    links: 
      - db
    ports:
      - "8080:5000"
  db:
    container_name: db
    image: "mysql/mysql-server:8.0.26"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  fillr:
    container_name: fillr
    build:
      context: ./UserFiller/
      dockerfile: ./Dockerfile
    environment:
      - FILLR__User__UserName=${FILLR__User__UserName}
      - FILLR__User__Email=${FILLR__User__Email}
      - FILLR__User__Password=${FILLR__User__Password}
      - FILLR__Connection__WebApi=${FILLR__Connection__WebApi}
    depends_on:
      - web
    links:
      - web
    

